/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.foobar2000.api;

public class bit_array_range extends bit_array {
  private long swigCPtr;

  public bit_array_range(long cPtr, boolean cMemoryOwn) {
    super(foobarJNI.SWIGbit_array_rangeUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(bit_array_range obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      foobarJNI.delete_bit_array_range(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public bit_array_range(long first, long count, boolean p_state) {
    this(foobarJNI.new_bit_array_range__SWIG_0(first, count, p_state), true);
  }

  public bit_array_range(long first, long count) {
    this(foobarJNI.new_bit_array_range__SWIG_1(first, count), true);
  }

  public boolean get(long n) {
    return foobarJNI.bit_array_range_get(swigCPtr, this, n);
  }

}
