/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.foobar2000.api;

public class bit_array_xor extends bit_array {
  private long swigCPtr;

  public bit_array_xor(long cPtr, boolean cMemoryOwn) {
    super(foobarJNI.SWIGbit_array_xorUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(bit_array_xor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      foobarJNI.delete_bit_array_xor(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public bit_array_xor(bit_array p_a1, bit_array p_a2) {
    this(foobarJNI.new_bit_array_xor(bit_array.getCPtr(p_a1), p_a1, bit_array.getCPtr(p_a2), p_a2), true);
  }

  public boolean get(long n) {
    return foobarJNI.bit_array_xor_get(swigCPtr, this, n);
  }

}
