/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.foobar2000.api;

public class foobar {
  public static replaygain_info getReplaygain_info_invalid() {
    long cPtr = foobarJNI.replaygain_info_invalid_get();
    return (cPtr == 0) ? null : new replaygain_info(cPtr, false);
  }

}
