/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.foobar2000.api;

public class GUID {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public GUID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GUID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      foobarJNI.delete_GUID(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setData1(long value) {
    foobarJNI.GUID_Data1_set(swigCPtr, this, value);
  }

  public long getData1() {
    return foobarJNI.GUID_Data1_get(swigCPtr, this);
  }

  public void setData2(int value) {
    foobarJNI.GUID_Data2_set(swigCPtr, this, value);
  }

  public int getData2() {
    return foobarJNI.GUID_Data2_get(swigCPtr, this);
  }

  public void setData3(int value) {
    foobarJNI.GUID_Data3_set(swigCPtr, this, value);
  }

  public int getData3() {
    return foobarJNI.GUID_Data3_get(swigCPtr, this);
  }

  public void setData4(SWIGTYPE_p_unsigned_char value) {
    foobarJNI.GUID_Data4_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getData4() {
    long cPtr = foobarJNI.GUID_Data4_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public GUID() {
    this(foobarJNI.new_GUID(), true);
  }

}
