/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.foobar2000.api;

public class info_storage {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public info_storage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(info_storage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      foobarJNI.delete_info_storage(swigCPtr);
    }
    swigCPtr = 0;
  }

  public long add_item(String p_name, long p_name_length, String p_value, long p_value_length) {
    return foobarJNI.info_storage_add_item(swigCPtr, this, p_name, p_name_length, p_value, p_value_length);
  }

  public void remove_mask(bit_array p_mask) {
    foobarJNI.info_storage_remove_mask(swigCPtr, this, bit_array.getCPtr(p_mask), p_mask);
  }

  public long get_count() {
    return foobarJNI.info_storage_get_count(swigCPtr, this);
  }

  public String get_name(long p_index) {
    return foobarJNI.info_storage_get_name(swigCPtr, this, p_index);
  }

  public String get_value(long p_index) {
    return foobarJNI.info_storage_get_value(swigCPtr, this, p_index);
  }

  public void copy_from(file_info p_info) {
    foobarJNI.info_storage_copy_from(swigCPtr, this, file_info.getCPtr(p_info), p_info);
  }

  public info_storage() {
    this(foobarJNI.new_info_storage(), true);
  }

}
