/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.foobar2000.api;

public class meta_storage {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public meta_storage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(meta_storage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      foobarJNI.delete_meta_storage(swigCPtr);
    }
    swigCPtr = 0;
  }

  public meta_storage() {
    this(foobarJNI.new_meta_storage(), true);
  }

  public long add_entry(String p_name, long p_name_length, String p_value, long p_value_length) {
    return foobarJNI.meta_storage_add_entry(swigCPtr, this, p_name, p_name_length, p_value, p_value_length);
  }

  public void insert_value(long p_index, long p_value_index, String p_value, long p_value_length) {
    foobarJNI.meta_storage_insert_value(swigCPtr, this, p_index, p_value_index, p_value, p_value_length);
  }

  public void modify_value(long p_index, long p_value_index, String p_value, long p_value_length) {
    foobarJNI.meta_storage_modify_value(swigCPtr, this, p_index, p_value_index, p_value, p_value_length);
  }

  public void remove_values(long p_index, bit_array p_mask) {
    foobarJNI.meta_storage_remove_values(swigCPtr, this, p_index, bit_array.getCPtr(p_mask), p_mask);
  }

  public void remove_mask(bit_array p_mask) {
    foobarJNI.meta_storage_remove_mask(swigCPtr, this, bit_array.getCPtr(p_mask), p_mask);
  }

  public void copy_from(file_info p_info) {
    foobarJNI.meta_storage_copy_from(swigCPtr, this, file_info.getCPtr(p_info), p_info);
  }

  public void reorder(SWIGTYPE_p_unsigned_int p_order) {
    foobarJNI.meta_storage_reorder(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(p_order));
  }

  public long get_count() {
    return foobarJNI.meta_storage_get_count(swigCPtr, this);
  }

  public String get_name(long p_index) {
    return foobarJNI.meta_storage_get_name(swigCPtr, this, p_index);
  }

  public String get_value(long p_index, long p_value_index) {
    return foobarJNI.meta_storage_get_value(swigCPtr, this, p_index, p_value_index);
  }

  public long get_value_count(long p_index) {
    return foobarJNI.meta_storage_get_value_count(swigCPtr, this, p_index);
  }

}
