/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.foobar2000.api;

public class PfcString {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public PfcString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PfcString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      foobarJNI.delete_PfcString(swigCPtr);
    }
    swigCPtr = 0;
  }

  public String toString() {
    return foobarJNI.PfcString_toString(swigCPtr, this);
  }

  public PfcString() {
    this(foobarJNI.new_PfcString(), true);
  }

}
